backend:
  name: git-gateway
  branch: 2.5-stable

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list", required: false, hint: "Es: misc, news, blog" }
      - { label: "Author", name: "author", widget: "relation", collection: "authors", search_fields: ["name"], value_field: "id", display_fields: ["name"] }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pagine"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

- name: "authors"
  label: "Autori"
  folder: "_authors"
  create: true
  slug: "{{slug}}"
  fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
    - { label: "Name", name: "name", widget: "string" }
    - { label: "ID", name: "id", widget: "string", hint: "Usato per collegare l'autore ai post (es. m8d)" }
    - { label: "Bio", name: "bio", widget: "text", required: false }
    - { label: "Avatar", name: "avatar", widget: "image", required: false }
    - { label: "Email", name: "email", widget: "string", required: false }
    - { label: "Website", name: "website", widget: "string", required: false }
